// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwejhklwrkjafnswmehq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZWpoa2x3cmtqYWZuc3dtZWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzgyNjAsImV4cCI6MjA2Mjg1NDI2MH0.pXFoilVV8-oh20EsQprUI6Jc-xqulVGc-MVBMmuj9mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);